version: '3'

services:
  jupyterlab1:
    build: jlab
    image: jlab_img
    container_name: jupyterlab1
    environment:
      - GRANT_SUDO=yes
    user: root
    volumes:
      - "/home/jphillips:/home/jovyan/work"
    ports:
      - "9000:8888"
    restart: on-failure

  jupyterlab2:
    build: jlab
    image: jlab_img
    container_name: jupyterlab2
    environment:
      - GRANT_SUDO=yes
    user: root
    volumes:
      - "/home/jphillips:/home/jovyan/work"
    restart: on-failure
